package sol3675.rlttweaks.references;

import net.minecraftforge.fml.common.ModMetadata;

public class ModInfo
{
    public static final String MODID = "rlttweaks";
    public static final String MODNAME = "RLT Tweaks";
    public static final String VERSION = "1.0.0";

    public static void loadInfo(ModMetadata meta)
    {
        meta.modId = MODID;
        meta.name = MODNAME;
        meta.description = "This mod created for the modpack called Refind Lost Technologies";
        meta.version = VERSION;
        meta.url = "TO-DO";
        meta.authorList.add("SOL3675");
        meta.autogenerated = false;
    }
}
